export interface EventItem {
  incident_id: string;
  timestamp: string;
  platform: string;
  incidentName: string;
  severity: "Low" | "Medium" | "High" | "Critical";
  status: "Open" | "In Progress" | "Resolved" | "New";
  description: string;
  source: string;
  customerName: string;
  
}

export const sampleEvents: EventItem[] = [
  {
    incident_id: "WB-21683-20250909-00010",
    timestamp: "2025-09-09T03:14:10Z",
    platform: "Trend Micro",
    severity: "Critical",
    status: "Open",
    incidentName: "Malicious Activity Detected",
    description: "Credential theft behavior detected.",
    source: "DESKTOP-001 • johndoe@company.com",
    customerName: "Acme Corp",
  },
  {
    incident_id: "866602",
    timestamp: "2025-07-29T11:31:24Z",
    platform: "QRadar",
    severity: "High",
    status: "Open",
    incidentName: "Concurrent Sessions Above Threshold",
    description: "Possible DoS attempt detected.",
    source: "Fortigate SOC • alice@company.com",
    customerName: "Beta Inc",
  },
  {
    incident_id: "119",
    timestamp: "2025-11-30T22:08:53Z",
    platform: "Cortex",
    severity: "Low",
    status: "Resolved",
    incidentName: "Local Threat Detected",
    description: "Blocked malware execution.",
    source: "XDR Agent pkp-prod1 • bob@company.com",
    customerName: "Gamma LLC",
  },

  {
    incident_id: "WB-21541-20251028-00016",
    timestamp: "2025-10-28T19:06:24Z",
    platform: "Trend Micro",
    severity: "Low",
    status: "Open",
    incidentName: "Data Destruction via DD Command - Unix",
    description: "Overwrites and deletes a file using DD in Unix.",
    source: "unix-server01",
    customerName: "YPPB",
  },

  {
    incident_id: "WB-21683-20251112-00007",
    timestamp: "2025-11-12T12:26:23Z",
    platform: "Trend Micro",
    severity: "High",
    status: "Open",
    incidentName: "Suspicious Deletion of Volume Shadow Copy",
    description: "Volume shadow copies were deleted, a possible sign of ransomware behavior.",
    source: "DESKTOP-002",
    customerName: "Felcra",
  },

  {
    incident_id: "131",
    timestamp: "2025-06-15T08:45:12Z",
    platform: "Cortex",
    severity: "High",
    status: "New",
    incidentName: "--",
    description: "'Local Threat Detected' generated by XDR Agent detected on host pkp-prod1 involving user apache",
    source: "SERVER-DB01",
    customerName: "--",
  },


  
];
